apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc
spec:
  replicas: 5
  selector:
    app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
        - name: myrccont
          image: nginx
          ports:
            - containerPort: 80

