apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-rolebinding
  namespace: webapp
roleRef:
  apiGroup: rbac.authorization.k8s.io 
  kind: Role
  name: app-role
subjects:
- namespace: webapp
  kind: ServiceAccount
  name: mysvc

