apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mystatefullset
spec:
  replicas: 4
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
        - name: contsf1
          image: nginx
          ports:
            - containerPort: 80
